apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keda
  namespace: flux-system
  labels:
    gwcp.guidewire.com/version: {{ .Values.keda.version | quote }}
    gwcp.guidewire.com/dept: {{ .Values.keda.departmentCode | quote }}
    gwcp.guidewire.com/maintained-by: {{ .Values.keda.podName | quote }}
    gwcp.guidewire.com/created-by: {{ .Values.keda.podName | quote }}
    gwcp.guidewire.com/app-name: {{ .Values.keda.appName | quote }}
    gwcp.guidewire.com/tenant-name: quadrant-shared
spec:
  interval: 15m
  url: https://kedacore.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
  labels:
    gwcp.guidewire.com/version: {{ .Values.keda.version | quote }}
    gwcp.guidewire.com/dept: {{ .Values.keda.departmentCode | quote }}
    gwcp.guidewire.com/maintained-by: {{ .Values.keda.podName | quote }}
    gwcp.guidewire.com/created-by: {{ .Values.keda.podName | quote }}
    gwcp.guidewire.com/app-name: {{ .Values.keda.appName | quote }}
    gwcp.guidewire.com/tenant-name: quadrant-shared
  annotations:
    meta.helm.sh/release-name: keda-release
spec:
  releaseName: keda
  targetNamespace: {{ .Values.namespace.name }}
  interval: 15m
  chart:
    spec:
      chart: keda
      version: {{ .Values.keda.version | quote }}
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
      interval: 15m
      dependsOn:
        - name: keda-namespace-component
  values:
    additionalLabels:
      gwcp.guidewire.com/version: {{ .Values.keda.version | quote }}
      gwcp.guidewire.com/dept: {{ .Values.keda.departmentCode | quote }}
      gwcp.guidewire.com/maintained-by: {{ .Values.keda.podName | quote }}
      gwcp.guidewire.com/created-by: {{ .Values.keda.podName | quote }}
      gwcp.guidewire.com/app-name: {{ .Values.keda.appName | quote }}
      gwcp.guidewire.com/tenant-name: quadrant-shared
    operator:
      name: keda-operator
      replicaCount: {{ .Values.keda.operator.replicaCount | quote }}
    metricsServer:
      replicaCount: {{ .Values.keda.metricsServer.replicaCount }}
    podDisruptionBudget:
      operator:
        minAvailable: 1
      metricServer:
        minAvailable: 1
    podAnnotations:
      keda:
        sidecar.istio.io/inject: "false"
      metricsAdapter:
        sidecar.istio.io/inject: "false"
    resources:
      operator:
        {{- toYaml .Values.keda.resources.operator | nindent 9 }}
      metricServer:
        {{- toYaml .Values.keda.resources.metricServer | nindent 9 }}