apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keda
  namespace: flux-system
  labels:
    gwcp.guidewire.com/version: "2.9.2"
    gwcp.guidewire.com/dept: "275"
    gwcp.guidewire.com/maintained-by: "pod-abcd"
    gwcp.guidewire.com/created-by: "pod-abcd"
    gwcp.guidewire.com/app-name: "keda"
    gwcp.guidewire.com/tenant-name: quadrant-shared
spec:
  interval: 5m
  url: https://kedacore.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
  labels:
    gwcp.guidewire.com/version: "2.9.2"
    gwcp.guidewire.com/dept: "275"
    gwcp.guidewire.com/maintained-by: "pod-abcd"
    gwcp.guidewire.com/created-by: "pod-abcd"
    gwcp.guidewire.com/app-name: "keda"
    gwcp.guidewire.com/tenant-name: quadrant-shared
  annotations:
    meta.helm.sh/release-name: keda-release
spec:
  releaseName: keda
  targetNamespace: keda-system
  interval: 2m0s
  chart:
    spec:
      chart: keda
      version: 2.9.2
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
      interval: 10m0s
  values:
    additionalLabels:
      gwcp.guidewire.com/version: "2.9.2"
      gwcp.guidewire.com/dept: "275"
      gwcp.guidewire.com/maintained-by: "pod-abcd"
      gwcp.guidewire.com/created-by: "pod-abcd"
      gwcp.guidewire.com/app-name: "keda"
      gwcp.guidewire.com/tenant-name: quadrant-shared
    operator:
      name: keda-operator
      replicaCount: 3
    metricsServer:
      replicaCount: 3
    podDisruptionBudget:
      operator:
        minAvailable: 1
      metricServer:
        minAvailable: 1
    podAnnotations:
      keda:
        sidecar.istio.io/inject: "false"
      metricsAdapter:
        sidecar.istio.io/inject: "false"
    resources:
      operator:
        limits:
          cpu: 100m
          memory: 1024Mi
        requests:
          cpu: 50m
          memory: 128Mi
      metricServer:
        limits:
          cpu: 100m
          memory: 1024Mi
        requests:
          cpu: 50m
          memory: 128Mi