---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keda-namespace-component
  namespace: default
spec:
  interval: 10m0s
  url: https://sundarok.github.io/atmos-namespace
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda-namespace-component
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: atmos-namespace
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: keda-namespace
      version: {{ .Values.namespace.version | quote }}
  values: {{ toYaml .Values.namespace | nindent 4 }}
